export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Mentorship',
    headline: 'Find a Life Coach Today',
    description: 'Build your future with our mentors to guide you through the next phase of your life',
    buttonLabel: 'Get Started',
    imgStart: true,
    img: require('../../images/svg-1.svg').default,
    alt: "Life Coaching",
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Premium Mentorship',
    headline: 'Find a Life Coach Today',
    description: 'Build your future with our mentors to guide you through the next phase of your life',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../images/svg-2.svg').default,
    alt: "Life Coaching",
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjThree = {
    id: 'signup',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Mentorship',
    headline: 'Find a Life Coach Today',
    description: 'Build your future with our mentors to guide you through the next phase of your life',
    buttonLabel: 'Get Started',
    imgStart: true,
    img: require('../../images/svg-3.svg').default,
    alt: "Life Coaching",
    dark: true,
    primary: true,
    darkText: false,
};